### ISSUE TITLE
章節過多時應添加 sleep (linovelib)

### ISSUE THREAD

**Issue by Kuan-Lun** [lightnovel-center/linovelib2epub#26]
我發現當章節超過四個時，會得出下述結果。而只要於每一次抓取後加上 sleep 就好了 (個人使用五秒暫停)。

> Traceback (most recent call last):
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 244, in _expand_paginated_chapter_links
    raise Exception(f'[ERROR]: request {url_next} failed.')
Exception: [ERROR]: request [url] failed.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
  File "[path]\linovelib2epub-main\main.py", line 6, in <module>
    linovelib_epub.run()
  File "[path]\linovelib2epub-main\src\linovelib2epub\linovel.py", line 405, in run
    novel = self._spider.fetch()
            ^^^^^^^^^^^^^^^^^^^^
>   File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 47, in fetch
    novel_whole = self._fetch()
                  ^^^^^^^^^^^^^
   File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 395, in _fetch
    new_novel_with_content = self._crawl_book_content(book_catalog_url)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 167, in _crawl_book_content
    url_next = self._expand_paginated_chapter_links(catalog_chapter, url_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 251, in _expand_paginated_chapter_links
    raise Exception(f'[ERROR]: request {url_next} failed.')
Exception: [ERROR]: request [url] failed.

**Comment by wdpm** [comment]
该bug能否被稳定复现？方便提供你运行的环境以及运行的代码吗？

**Comment by Kuan-Lun** [comment]
> 该bug能否被稳定复现？方便提供你运行的环境以及运行的代码吗？

3674 總是於 第04話 然後結成了新的因緣 (第五個章節) 跳出錯誤，能穩地復現。

環境是 Python 3.11.7

sleep 的插入如下
> #linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py
> def _expand_paginated_chapter_links(self, chapter: CatalogLinovelibMobileChapter, url_next):
        from time import sleep
        sleep(5)

**Comment by wdpm** [comment]
## 问题复现
首先，我在本地测试尝试复现，没有遇到运行中断的问题。下面是日志。
```bash
2023-12-27,17:11:50 INFO     LinovelibMobileSpider Succeed to get the novel of book_id: 3674                                                            linovelib_mobile_spider.py:78
2023-12-27,17:11:51 INFO     LinovelibMobileSpider Succeed to get the catalog of book_id: 3674                                                         linovelib_mobile_spider.py:136
                    INFO     LinovelibMobileSpider volume: 女友・交换                                                                                  linovelib_mobile_spider.py:152
                    INFO     LinovelibMobileSpider chapter : 作品相关                                                                                  linovelib_mobile_spider.py:164
2023-12-27,17:11:52 INFO     LinovelibMobileSpider Processing page... https://www.bilinovel.com/novel/3674/186502.html                                 linovelib_mobile_spider.py:206
                    INFO     LinovelibMobileSpider chapter : 第01话 在意外的相遇中蒙混过关*                                                            linovelib_mobile_spider.py:164
2023-12-27,17:11:53 INFO     LinovelibMobileSpider Processing page... https://www.bilinovel.com/novel/3674/186503.html                                 linovelib_mobile_spider.py:206
2023-12-27,17:11:54 INFO     LinovelibMobileSpider Processing page... https://www.bilinovel.com/novel/3674/186503_2.html                               linovelib_mobile_spider.py:206
                    INFO     LinovelibMobileSpider chapter : 第02话 XXXXXXXXXXX                                                           linovelib_mobile_spider.py:164
2023-12-27,17:11:55 INFO     LinovelibMobileSpider Processing page... https://www.bilinovel.com/novel/3674/186504.html                                 linovelib_mobile_spider.py:206
                    INFO     LinovelibMobileSpider chapter : 第03话 XXXXXXXXXX                                                     linovelib_mobile_spider.py:164
2023-12-27,17:11:56 INFO     LinovelibMobileSpider Processing page... https://www.bilinovel.com/novel/3674/186505.html                                 linovelib_mobile_spider.py:206
                    INFO     LinovelibMobileSpider chapter : 第04话 然后结成了新的因缘                                                                 linovelib_mobile_spider.py:164
2023-12-27,17:11:57 INFO     LinovelibMobileSpider Processing page... https://www.bilinovel.com/novel/3674/186506.html                                 linovelib_mobile_spider.py:206
                    INFO     LinovelibMobileSpider chapter : 第05话 我，确实是男朋友吧？                                                               linovelib_mobile_spider.py:164
2023-12-27,17:11:58 INFO     LinovelibMobileSpider Processing page... https://www.bilinovel.com/novel/3674/186507.html                                 linovelib_mobile_spider.py:206
......
```
因此，这是一个可能涉及网络请求次数，以及对方服务器linovelib请求限流的问题。

## 分析
根据你提供的报错trackback，我提取关键源码进行分析
```python
    def _expand_paginated_chapter_links(self, chapter: CatalogLinovelibMobileChapter, url_next):
        # fix broken links in place(catalog_lis) if exits
        # - if chapter[1] is valid link, assign it to url_next
        # - if chapter[1] is not a valid link,e.g. "javascript:cid(0)" etc. use url_next
        if not self._is_valid_chapter_link(chapter.chapter_url):
            # now the url_next value is the correct link of of chapter[1].
            chapter.chapter_url = url_next
        else:
            url_next = chapter.chapter_url

        # goal: solve all page links of a certain chapter
        while True:
            resp = requests_get_with_retry(self.session, url_next, logger=None)
            if resp:
                soup = BeautifulSoup(resp.text, 'lxml')
            else:
                raise Exception(f'[ERROR]: request {url_next} failed.')   <------------这里

            first_script = soup.find("body", {"id": "aread"}).find("script")
            first_script_text = first_script.text
            # alternative: use split(':')[-1] to get read_params_text
            read_params_text = first_script_text[len('var ReadParams='):]
            read_params_json = demjson3.decode(read_params_text)
            url_next = urljoin(f'{self.spider_settings["base_url"]}/novel', read_params_json['url_next'])

            if '_' in url_next:
                chapter.add_expand_paginated_chapter_url(url_next)
            else:
                break

        return url_next
```
主要是这个请求重试的逻辑
```python
    while True:
            resp = requests_get_with_retry(self.session, url_next, logger=None)
            if resp:
                soup = BeautifulSoup(resp.text, 'lxml')
            else:
                raise Exception(f'[ERROR]: request {url_next} failed.') 
```
继续定位到 requests_get_with_retry，这里面的错误尝试等待为1s
```python
    while current_num_of_request <= retry_max:
        try:
            response = client.get(url, headers=headers, timeout=timeout)
            if response:
                return response
            else:
                if logger:
                    logger.warning(f'Request {url} succeed but data is empty.')
                time.sleep(1)  <-----------------等待
        except (Exception,) as e:
            if logger:
                logger.error(f'Request {url} failed.', e)
            time.sleep(1) <------------------等待

        current_num_of_request += 1
        if logger:
            logger.warning(f'current_num_of_request: {current_num_of_request}')
```
因此，我推测是部分网络环境下，在 retry_max（默认为5）次重试之后，依旧拿不到正常的请求结果，程序被迫中断。
而增大间隔的等待，例如你提议的5s，可以使得重试的请求大概率能够拿到正常的服务器响应。

## 设计权衡
问题的解决方案似乎是**增加重试请求之间的等待时长**。

另外，增加请求等待的逻辑应该在 `requests_get_with_retry()`方法中修改，也就是在网络工具层，不应该扩散到业务层（这里是具体的爬虫处理层）。

常规做法有：
- 基于经验的固定间隔，例如3s，5s。
- 基于指数退避的间隔，参考[指数退避算法](https://cloud.google.com/memorystore/docs/redis/exponential-backoff?hl=zh-cn#example_algorithm)

  ```bash
  min(((2^n)+random_number_milliseconds), maximum_backoff)
  ```
  指数退避算法可以有效估计当前服务器的负载处理能力。避免了固定间隔的死板做法。我倾向于使用这种策略。

后续我会更新代码，请留意更新。如果你对此修改有更好的建议，欢迎讨论。

**Comment by wdpm** [comment]
@Kuan-Lun 已尝试修复，请更新源码进行检查。

**Comment by Kuan-Lun** [comment]
> @Kuan-Lun 已尝试修复，请更新源码进行检查。

已確認當前更新有效。

**Comment by wdpm** [comment]
> > @Kuan-Lun 已尝试修复，请更新源码进行检查。
> 
> 已確認當前更新有效。

好，那我就关闭该issue了。
