### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'children'

### ISSUE THREAD

**Issue by Kuan-Lun** [lightnovel-center/linovelib2epub#32]
ID 3087

錯誤訊息如下：
```
2024-02-13,15:44:44 INFO     LinovelibMobileSpider Succeed to get the     linovelib_mobile_spider.py:80
                             novel of book_id: 3087
                    INFO     LinovelibMobileSpider Succeed to get the    linovelib_mobile_spider.py:138
                             catalog of book_id: 3087
Traceback (most recent call last):
  File "[path]\linovelib2epub-main\main.py", line 6, in <module>
    linovelib_epub.run()
  File "[path]\linovelib2epub-main\src\linovelib2epub\linovel.py", line 405, in run
    novel = self._spider.fetch()
            ^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 49, in fetch
    novel_whole = self._fetch()
                  ^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 399, in _fetch
    new_novel_with_content = self._crawl_book_content(book_catalog_url)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 141, in _crawl_book_content
    catalog_list: List[CatalogLinovelibMobileVolume] = self._convert_to_catalog_list(catalog_html)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 326, in _convert_to_catalog_list
    catalog_html_items = catalog_wrapper.children  # Use children to get both <h3> and <li> elements
                         ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'children'
```

我把 _convert_to_catalog_list 的輸入 catalog_html 存下來，參見 ~~Gofile~~。方式為如下：
```
with open('catalog_html.txt', mode='a+', encoding='utf8') as f:
    f.write(catalog_html)
```

**Comment by Kuan-Lun** [comment]
> @Kuan-Lun 已修复，请更新源码来检验。

已確認，可正常使用。
