### ISSUE TITLE
MasiroSpider Request https://masiro.me/admin/auth/login succeed but status code is 403.

### ISSUE THREAD

**Issue by Kuan-Lun** [lightnovel-center/linovelib2epub#33]
出現 403 錯誤，完整訊息如下：

```
(.venv) PS [path]\linovelib2epub-main> python .\main.py
2024-02-18,02:55:00 WARNING  MasiroSpider Request https://masiro.me/admin/auth/login succeed but status     utils.py:105
                             code is 403.
2024-02-18,02:55:01 WARNING  MasiroSpider current_num_of_request: 1                                         utils.py:114
2024-02-18,02:55:02 WARNING  MasiroSpider Request https://masiro.me/admin/auth/login succeed but status     utils.py:105
                             code is 403.
2024-02-18,02:55:03 WARNING  MasiroSpider current_num_of_request: 2                                         utils.py:114
                    WARNING  MasiroSpider Request https://masiro.me/admin/auth/login succeed but status     utils.py:105
                             code is 403.
2024-02-18,02:55:04 WARNING  MasiroSpider current_num_of_request: 3                                         utils.py:114
                    WARNING  MasiroSpider Request https://masiro.me/admin/auth/login succeed but status     utils.py:105
                             code is 403.
2024-02-18,02:55:05 WARNING  MasiroSpider current_num_of_request: 4                                         utils.py:114
2024-02-18,02:55:06 WARNING  MasiroSpider Request https://masiro.me/admin/auth/login succeed but status     utils.py:105
                             code is 403.
2024-02-18,02:55:07 WARNING  MasiroSpider current_num_of_request: 5                                         utils.py:114
                    WARNING  MasiroSpider Request https://masiro.me/admin/auth/login succeed but status     utils.py:105
                             code is 403.
2024-02-18,02:55:08 WARNING  MasiroSpider current_num_of_request: 6                                         utils.py:114
Traceback (most recent call last):
  File "[path]\linovelib2epub-main\main.py", line 28, in <module>
    linovelib_epub.run()
  File "[path]\linovelib2epub-main\src\linovelib2epub\linovel.py", line 405, in run
    novel = self._spider.fetch()
            ^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\masiro_spider.py", line 49, in fetch
    novel = asyncio.run(self._fetch())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\masiro_spider.py", line 67, in _fetch
    login_info = await self._login(session)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\masiro_spider.py", line 98, in _login
    await self._masiro_get_token(login_info, session)
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\masiro_spider.py", line 453, in _masiro_get_token
    page_body = html.fromstring(res)
                ^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\.venv\Lib\site-packages\lxml\html\__init__.py", line 872, in fromstring
    is_full_html = _looks_like_full_html_unicode(html)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

因為我經由瀏覽器可以正常訪問 (含登入後瀏覽文章) masiro.me，所以我的網路環境是沒有問題的。

**Comment by wdpm** [comment]
![image](https://github.com/lightnovel-center/linovelib2epub/assets/14016242/c1abaf89-44c8-428e-8ee7-98a3531af688)

上图是在浏览器访问时的截图，是cloudflare的检测拦截。
而目前该项目对masiro的爬虫并没有处理关于cloudflare的拦截问题，因此访问不到。
该问题我暂时没有较好的免费解决方式，当然，有些第三方服务专门提供过cloudflare检测的付费服务，但是这对于一个非盈利的开源小项目来说太不切实际了。

如果你有较好解决方案，或者其他想法，可以在下面继续讨论，此issue暂时保持打开状态就行。
@Kuan-Lun

**Comment by wdpm** [comment]
付费的过cloudflare检测，稍微找了下，例如这个 [capsolver](https://www.capsolver.com/#pricing)

这个问题本质是希望寻找一个较好的solve Cloudflare challenge的方案。

**Comment by wdpm** [comment]
![image](https://github.com/lightnovel-center/linovelib2epub/assets/14016242/35131aad-fe96-485d-84f2-4e8fcd4321da)

希望渺茫。白嫖党输麻了属于是。
![image](https://github.com/lightnovel-center/linovelib2epub/assets/14016242/41b0dce7-3d6a-47c3-b475-b11a1410495e)

**Comment by Kuan-Lun** [comment]
如果使用本地的 cookie，或跳開視窗讓使用者點機驗證如何？
那個驗證動作只有開始進入時才需要，後續還是可以讓程式繼續批量下載內容。

**Comment by wdpm** [comment]
> 如果使用本地的 cookie，或跳開視窗讓使用者點擊驗證如何？ 那個驗證動作只有開始進入時才需要，後續還是可以讓程式繼續批量下載內容。

无头浏览器理论上可行，例如 selenium 或者 puppeteer，但是有待研究。不到万不得已，我不会选用这种方式的。
这种方式会极大地增加该项目的依赖，而且使用1步骤也会变得麻烦一点。

**Comment by wdpm** [comment]
@Kuan-Lun 经过一番对无头浏览器的探索（例如：https://github.com/g1879/DrissionPage/issues?q=cloudflare ）以及在本地的尝试，目前可以推测无头浏览器方案可行。但是需要变动较多代码，耐心等待后续修复吧。

**Comment by wdpm** [comment]
最新进展
![image](https://github.com/lightnovel-center/linovelib2epub/assets/14016242/6a83272f-4149-447b-abe0-286bba441637)

**Comment by wdpm** [comment]
@Kuan-Lun 已初步重构完毕，理论上已经成功修复。你需要更新代码，更新依赖，并且需要保证chrome路径正确。

**Comment by Kuan-Lun** [comment]
```
(.venv) PS [path]\linovelib2epub-main> python .\main.py
Traceback (most recent call last):
  File "[path]\linovelib2epub-main\main.py", line 24, in <module>
    from linovelib2epub import Linovelib2Epub
ModuleNotFoundError: No module named 'linovelib2epub'
(.venv) PS [path]\linovelib2epub-main> ls

    Directory: [path]\linovelib2epub-main

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----         2024/2/22 下午 10:00                .github
d----         2024/2/22 下午 10:04                .venv
d----         2024/2/22 下午 09:59                analyze
d----         2024/2/22 下午 09:59                docs-internal
d----         2024/2/22 下午 10:00                playground
d----         2024/2/22 下午 10:00                src
d----         2024/2/22 下午 10:00                test
-a---         2024/2/21 下午 11:57           2289 .all-contributorsrc
-a---         2024/2/21 下午 11:57            563 .gitignore
-a---         2024/2/18 上午 02:52             89 .secrets.toml
-a---         2024/2/21 下午 11:57             50 .tokeignore
-a---         2024/2/21 下午 11:57          34515 LICENSE
-a---         2024/2/22 下午 10:13            903 main.py
-a---         2024/2/21 下午 11:57          15978 merrli.png
-a---         2024/2/21 下午 11:57        3608732 preview.gif
-a---         2024/2/21 下午 11:57           2744 pyproject.toml
-a---         2024/2/21 下午 11:57          17164 README.md
-a---         2024/2/21 下午 11:57            126 requirements_dev.txt
-a---         2024/2/21 下午 11:57            250 requirements.txt
-a---         2024/2/21 下午 11:57          27950 tearlaments-ban.png
-a---         2024/2/21 下午 11:57            511 tox.ini
```

新版本好像不能 `import linovelib2epub`

我與之前依樣都是依循你說明中的 "install from source" 步驟

**Comment by wdpm** [comment]
有点诡异，我没改api，理论上不应该出现这个错误。

**Comment by Kuan-Lun** [comment]
我把整個資料夾 (linovelib2epub-main) 刪掉，從頭解壓縮一個新資料夾後的就可以了。
也許是某個東西衝突到 (?)

已確認當前版本是可以正常抓取 masiro。
