### ISSUE TITLE
章節過多時容易引發 Exception: [ERROR]: request [url] failed.

### ISSUE THREAD

**Issue by Kuan-Lun** [lightnovel-center/linovelib2epub#34]
嗶哩的 ID 2978，共 431 章。
我跑第四次才能一次跑完
[大概跑約 300 章會因錯誤停止]

```
Traceback (most recent call last):
  File "[path]\linovelib2epub-main\main.py", line 28, in <module>
    linovelib_epub.run()
  File "[path]\linovelib2epub-main\src\linovelib2epub\linovel.py", line 405, in run
    novel = self._spider.fetch()
            ^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 49, in fetch
    novel_whole = self._fetch()
                  ^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 402, in _fetch
    new_novel_with_content = self._crawl_book_content(book_catalog_url)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\linovelib2epub-main\src\linovelib2epub\spider\linovelib_mobile_spider.py", line 181, in _crawl_book_content
    raise Exception(f'[ERROR]: request {page_link} failed.')
Exception: [ERROR]: request [url] failed.
```

我不確定是不是有設定錯誤幾次就終止；
但如果有的話，我建議根據總章節數來適當增加可重試的次數。

**Comment by wdpm** [comment]
![image](https://github.com/lightnovel-center/linovelib2epub/assets/14016242/f680e95c-15d1-458d-88e4-f812937490ae)

从你的报错log中，我定位到上面的代码段。可以看出是请求某个page_link时失败了。
在之前的请求重试逻辑中，对于某个HTTP请求，请求重试的最大次数默认为5，加上1个原请求，也就是6个请求。
如果这6个请求全都失败了，那就直接退出程序。

而你上面的报错案例，大概率就是网络不太稳定，导致6次请求全都失败了。

这可以通过一个参数来设置更大的重试次数。

```python
from linovelib2epub import Linovelib2Epub

if __name__ == '__main__':
    linovelib_epub = Linovelib2Epub(book_id=2978, http_retries=20)
    linovelib_epub.run()
```

在之后的更新中，我会考虑修改这个项目的请求重试的默认值，将其提升到10。
@Kuan-Lun

**Comment by Kuan-Lun** [comment]
不行，會一直跳下面這段畫面

```
                    INFO     LinovelibMobileSpider SUCCEED_COUNT: 56                                  base_spider.py:152
                    INFO     LinovelibMobileSpider [NEXT TURN]Pending task count: 2                   base_spider.py:153
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYz9n.jpg; should retry.
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYIus.jpg; should retry.
                    INFO     LinovelibMobileSpider SUCCEED_COUNT: 56                                  base_spider.py:152
                    INFO     LinovelibMobileSpider [NEXT TURN]Pending task count: 2                   base_spider.py:153
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYz9n.jpg; should retry.
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYIus.jpg; should retry.
                    INFO     LinovelibMobileSpider SUCCEED_COUNT: 56                                  base_spider.py:152
                    INFO     LinovelibMobileSpider [NEXT TURN]Pending task count: 2                   base_spider.py:153
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYz9n.jpg; should retry.
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYIus.jpg; should retry.
                    INFO     LinovelibMobileSpider SUCCEED_COUNT: 56                                  base_spider.py:152
                    INFO     LinovelibMobileSpider [NEXT TURN]Pending task count: 2                   base_spider.py:153
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYz9n.jpg; should retry.
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYIus.jpg; should retry.
                    INFO     LinovelibMobileSpider SUCCEED_COUNT: 56                                  base_spider.py:152
                    INFO     LinovelibMobileSpider [NEXT TURN]Pending task count: 2                   base_spider.py:153
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYz9n.jpg; should retry.
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYIus.jpg; should retry.
                    INFO     LinovelibMobileSpider SUCCEED_COUNT: 56                                  base_spider.py:152
                    INFO     LinovelibMobileSpider [NEXT TURN]Pending task count: 2                   base_spider.py:153
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYIus.jpg; should retry.
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYz9n.jpg; should retry.
                    INFO     LinovelibMobileSpider SUCCEED_COUNT: 56                                  base_spider.py:152
                    INFO     LinovelibMobileSpider [NEXT TURN]Pending task count: 2                   base_spider.py:153
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYIus.jpg; should retry.
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYz9n.jpg; should retry.
                    INFO     LinovelibMobileSpider SUCCEED_COUNT: 56                                  base_spider.py:152
                    INFO     LinovelibMobileSpider [NEXT TURN]Pending task count: 2                   base_spider.py:153
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYIus.jpg; should retry.
                    ERROR    LinovelibMobileSpider Exception: ClientConnectorCertificateError | FAIL: base_spider.py:145
                             https://iili.io/JEbYz9n.jpg; should retry.
                    INFO     LinovelibMobileSpider SUCCEED_COUNT: 56                                  base_spider.py:152
                    INFO     LinovelibMobileSpider [NEXT TURN]Pending task count: 2                   base_spider.py:153
```

CTRL+C 終止的話，顯示如下

```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "\\KL-NAS\lan_klwang\linovelib2epub-main\linovelib2epub-main\src\linovelib2epub\spider\base_spider.py", line 128, in download_images_by_asyncio
    done, pending = await asyncio.wait(pending, return_when=asyncio.ALL_COMPLETED)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 428, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 535, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:\linovelib2epub-main\linovelib2epub-main\main.py", line 26, in <module>
    linovelib_epub.run()
  File "\\KL-NAS\lan_klwang\linovelib2epub-main\linovelib2epub-main\src\linovelib2epub\linovel.py", line 415, in run
    self._spider.post_fetch(novel)
  File "\\KL-NAS\lan_klwang\linovelib2epub-main\linovelib2epub-main\src\linovelib2epub\spider\base_spider.py", line 190, in post_fetch
    self._process_image_download(novel)
  File "\\KL-NAS\lan_klwang\linovelib2epub-main\linovelib2epub-main\src\linovelib2epub\spider\base_spider.py", line 216, in _process_image_download
    asyncio.run(_download_image(image_list))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
```

**Comment by Kuan-Lun** [comment]
一樣是 ID 2978

我測試了四次，發現該狀況可能為穩定發生。

簡單的解決方式是 CTRL+C 挑出後再執行第二次，是否繼續先前下載，選擇不要即可正常運作。
(但也有可能只是我剛好碰上可以正常運作的情形)

```
The last unfinished work was detected, continue with your last job? [y/n]: n
```

從錯誤訊息中觀察，都出現了 `https://iili.io/JEbYIus.jpg` 與 `https://iili.io/JEbYz9n.jpg` 這兩個網址，我想可能是這兩張圖的問題，或是 `iili.io` 的問題？
我人工觀察其他圖片，似乎其餘的都是使用 `img1.readpai.com` 而不是 `iili.io`，當然也有可能是我遺漏。

根據我調查，`iili.io` 是 `freeimage.host` (使用 Chevereto 圖床套件) 的 CDN 設定。有一種可能是機率性被機器人驗證機制擋住，我猜的。我並不是很確定，僅供參考。

**Comment by wdpm** [comment]
好的。你提供给我的信息已经非常充足了。
我会尝试在本地复现并解决这个问题。请留意后续更新即可。

**Comment by wdpm** [comment]
## 关于复现
![image](https://github.com/lightnovel-center/linovelib2epub/assets/14016242/d7b37424-dcde-4b0c-bf3e-95e647cad10f)
![image](https://github.com/lightnovel-center/linovelib2epub/assets/14016242/7c817123-4165-46d8-a689-50a1434e87da)

我在本地复现时，发现这两张图片下载正常。
这两张图片出自这个章节：【400 被囚禁的雷帝⑤】，链接分别为：
- https://iili.io/JEbYIus.jpg
- https://iili.io/JEbYz9n.jpg

## 分析
由于我本地复现失败，我不得不重新探索这个 ClientConnectorCertificateError 错误的发生原因。

我定位到了图片下载是使用aiohttp这个库，经过网上的一番搜索，结合 ClientConnectorCertificateError 名称，我推测是因为ssl证书问题。而且这个问题似乎在macos中会出现，而windows 10没有遇到这个问题。

## 可能的解决方案

- 第一种：明确禁用 aiohttp session 的 ssl 设置。

示例如下所示。
```python
import aiohttp
import asyncio

# see also https://stackoverflow.com/a/69605432

async def main(url):
    # 尝试下 ssl=True 会发生什么事情？是否还能正常下载？
    tcp_connector = aiohttp.TCPConnector(ssl=False)
    async with aiohttp.ClientSession(connector=tcp_connector) as session:
        async with session.get(url) as response:
            print("Status:", response.status)
            print("Content-type:", response.headers['content-type'])
            bytes = await response.read()
            print("Body:", len(bytes), "...")


url = 'https://iili.io/JEbYIus.jpg'
url2 = 'https://iili.io/JEbYz9n.jpg'

asyncio.run(main(url))
```
- 告知我你的PC 系统是macos还是其他？
- 尝试运行上面的代码，也试试 ssl=True 会发生什么情况。并将结果反馈给我。

---
- 第二种：安装ssl证书

首先你需要安装这个库
```python
# 必须在你的venv环境下，执行下面指令
pip install certifi
```
```python
import aiohttp
import asyncio
import ssl
import certifi

print(f'{certifi.where()=}')

async def main(url):
    ssl_context = ssl.create_default_context(cafile=certifi.where())
    conn = aiohttp.TCPConnector(ssl=ssl_context)

    async with aiohttp.ClientSession(connector=conn) as session:
        async with session.get(url) as response:
            print("Status:", response.status)


url = 'https://iili.io/JEbYIus.jpg'

loop = asyncio.get_event_loop()
loop.run_until_complete(main(url))
```

**Comment by Kuan-Lun** [comment]
我是 Win 11 x64

---
第一種方案
# ssl = False

```
Status: 200
Content-type: image/jpeg
Body: 248986 ...
```

# ssl = True

```
Traceback (most recent call last):
  File "[path]\.venv\Lib\site-packages\aiohttp\connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1113, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1146, in _create_connection_transport
    await waiter
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\sslproto.py", line 560, in _do_handshake
    self._sslobj.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'iili.io'. (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[path]\main.py", line 20, in <module>
    asyncio.run(main(url))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "[path]\main.py", line 10, in main
    async with session.get(url) as response:
  File "[path]\.venv\Lib\site-packages\aiohttp\client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "[path]\.venv\Lib\site-packages\aiohttp\client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\.venv\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\.venv\Lib\site-packages\aiohttp\connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\.venv\Lib\site-packages\aiohttp\connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "[path]\.venv\Lib\site-packages\aiohttp\connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\.venv\Lib\site-packages\aiohttp\connector.py", line 994, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host iili.io:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'iili.io'. (_ssl.c:1006)")]
```
---
第二種方案

```
certifi.where()='[path]\\.venv\\Lib\\site-packages\\certifi\\cacert.pem'
Traceback (most recent call last):
  File "[path]\.venv\Lib\site-packages\aiohttp\connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1113, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1146, in _create_connection_transport
    await waiter
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\sslproto.py", line 560, in _do_handshake
    self._sslobj.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'iili.io'. (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[path]\main.py", line 20, in <module>
    loop.run_until_complete(main(url))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "[path]\main.py", line 13, in main
    async with session.get(url) as response:
  File "[path]\.venv\Lib\site-packages\aiohttp\client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "[path]\.venv\Lib\site-packages\aiohttp\client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\.venv\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\.venv\Lib\site-packages\aiohttp\connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\.venv\Lib\site-packages\aiohttp\connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "[path]\.venv\Lib\site-packages\aiohttp\connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[path]\.venv\Lib\site-packages\aiohttp\connector.py", line 994, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host iili.io:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'iili.io'. (_ssl.c:1006)")]
```

**Comment by wdpm** [comment]
根据你上面的反馈，使用第一种方案的ssl=False可以快速解决这个问题。在这个项目中，在图片下载时配置ssl=False并没有太大的安全隐患，我认为可行。

请更新代码后，尝试这段代码来验证是否修复。
```python
from linovelib2epub import Linovelib2Epub

if __name__ == '__main__':
    linovelib_epub = Linovelib2Epub(book_id=2978, select_volume_mode=True)
    linovelib_epub.run()
```
由于这个2978很多卷，开启【选择卷】模式，只选择【第九章】即可。

**Comment by Kuan-Lun** [comment]
已確認，當前版本可正常運行。
