### ISSUE TITLE
[BUG] DrissionPage.errors.ElementNotFoundError

### ISSUE THREAD

**Issue by Kuan-Lun** [lightnovel-center/linovelib2epub#52]
**Describe the bug（描述这个BUG）**
進入指定ID主頁後，跳出錯誤顯示沒有需要的元素。
```
PS D:\linovelib2epub.clone> .venv\\Scripts\\python main.py
2024-10-23,16:46:52 INFO     LinovelibSpider _html_content_id=TextContent                                                                linovelib_spider.py:58
                    INFO     LinovelibSpider len(_mapping_dict)=0                                                                        linovelib_spider.py:60
                    INFO     LinovelibSpider navigator.language.toLowerCase()=zh-tw                                                     linovelib_spider.py:718
                    INFO     LinovelibSpider  初始化 Driver 完毕...                                                                     linovelib_spider.py:725
Traceback (most recent call last):
  File "D:\linovelib2epub.clone\main.py", line 33, in <module>
    linovelib_epub.run()
    ~~~~~~~~~~~~~~~~~~^^
  File "D:\linovelib2epub.clone\src\linovelib2epub\linovel.py", line 445, in run
    novel = self._spider.fetch()
  File "D:\linovelib2epub.clone\src\linovelib2epub\spider\linovelib_spider.py", line 84, in fetch
    novel_whole = self._fetch_pc()
  File "D:\linovelib2epub.clone\src\linovelib2epub\spider\linovelib_spider.py", line 994, in _fetch_pc
    self._convert_page_language_pc(book_url)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\linovelib2epub.clone\src\linovelib2epub\spider\linovelib_spider.py", line 1031, in _convert_page_language_pc
    current_text = translate_btn.text
                   ^^^^^^^^^^^^^^^^^^
  File "D:\linovelib2epub.clone\.venv\Lib\site-packages\DrissionPage\_elements\none_element.py", line 38, in __getattr__
    raise ElementNotFoundError(None, self.method, self.args)
DrissionPage.errors.ElementNotFoundError:
没有找到元素。
method: ele()
args: {'locator': '#GB_BIG', 'index': 1, 'timeout': 10}
```

**To Reproduce（复现步骤）**
复现的代码以及操作（例如分支选择、卷选择等等）

注意：请务必打开**DEBUG logging** 模式。示例代码：
```python
from linovelib2epub import Linovelib2Epub

if __name__ == "__main__":
    linovelib_epub = Linovelib2Epub(
        book_id=4126,
        select_volume_mode=True,
        log_level="DEBUG",
        target_site=TargetSite.LINOVELIB_PC_TRADITIONAL,
    )
    linovelib_epub.run()
```

**Expected behavior（期望的行为）**

**Screenshots or Video（截图或者视频录制）**
程式有正常開啟指定ID的頁面
![圖片](https://github.com/user-attachments/assets/064458d4-a87b-4ce7-8632-2870756497a7)
~~[HTML](https://www.example.com)~~

**Environment（软件环境）**
 - 网络环境: 台灣 (有依指示使用 TargetSite.LINOVELIB_PC_TRADITIONAL)
 - OS Verison:  例如：Windows 11 專業版, 24H2 (版本), 26100.2033 (OS 組鍵)
 - Python Version: 3.13
 - Pip Version: `pip 24.2 from D:\linovelib2epub.clone\.venv\Lib\site-packages\pip (python 3.13)`
 - Python packages: `pip list`
`requirements.txt` 中的版本太舊，且未註明需要的`setuptools`版本。如"pillow==10.1.0"無法正常安裝
```
Collecting pillow==10.1.0 (from -r requirements.txt (line 8))
  Using cached Pillow-10.1.0.tar.gz (50.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "D:\linovelib2epub.clone\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "D:\linovelib2epub.clone\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\linovelib2epub.clone\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\polyp\AppData\Local\Temp\pip-build-env-u4s2aofb\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\polyp\AppData\Local\Temp\pip-build-env-u4s2aofb\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires   
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\polyp\AppData\Local\Temp\pip-build-env-u4s2aofb\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 30, in <module>
        File "<string>", line 27, in get_version
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
故我修改 `requirements.txt`，將 `==` 改為 `>=`。
```
Package            Version     Editable project location
------------------ ----------- -------------------------
aiofiles           24.1.0
aiohappyeyeballs   2.4.3
aiohttp            3.10.10
aiosignal          1.3.1
ansicon            1.89.0
attrs              24.2.0
beautifulsoup4     4.12.3
blessed            1.20.0
Brotli             1.1.0
bs4                0.0.2
certifi            2024.8.30
cffi               1.17.1
charset-normalizer 3.4.0
click              8.1.7
colorama           0.4.6
cssselect          1.2.0
DataRecorder       3.6.2
demjson3           3.0.6
DownloadKit        2.0.5
DrissionPage       4.1.0.9
dynaconf           3.2.6
EbookLib           0.18
editor             1.6.6
esprima            4.0.1
et-xmlfile         1.1.0
fake-useragent     1.5.1
filelock           3.16.1
frozenlist         1.4.1
h11                0.14.0
idna               3.10
inquirer           3.4.0
jinxed             1.3.0
linovelib2epub     0.1.3       D:\linovelib2epub.clone
lxml               5.3.0
markdown-it-py     3.0.0
mdurl              0.1.2
multidict          6.1.0
openpyxl           3.1.5
outcome            1.3.0.post0
packaging          24.1
pillow             11.0.0
pip                24.2
propcache          0.2.0
psutil             6.1.0
pycparser          2.22
Pygments           2.18.0
PySocks            1.7.1
pytesseract        0.3.13
readchar           4.2.0
requests           2.32.3
requests-file      2.1.0
rich               13.9.3
runs               1.2.2
selenium           4.25.0
six                1.16.0
sniffio            1.3.1
sortedcontainers   2.4.0
soupsieve          2.6
tabulate           0.9.0
tldextract         5.1.2
trio               0.27.0
trio-websocket     0.11.1
typing_extensions  4.12.2
urllib3            2.2.3
uuid               1.30
wcwidth            0.2.13
websocket-client   1.8.0
wsproto            1.2.0
xmod               1.8.1
yarl               1.16.0
```

**Additional context（补充信息[可选]）**
我建議更新 `requirements.txt` 所要求的版本。

**Comment by wdpm** [comment]
- https://gofile.io/d/BsyAAb 这个html文件我无法访问，换一个网盘吧
- requirements.txt 中pillow版本同意更新到11.0+
- 找不到id的问题从下面的log中可以看到是timeout
```
PS D:\linovelib2epub.clone> .venv\\Scripts\\python main.py
2024-10-23,16:46:52 INFO     LinovelibSpider _html_content_id=TextContent                                                                linovelib_spider.py:58
                    INFO     LinovelibSpider len(_mapping_dict)=0                                                                        linovelib_spider.py:60
                    INFO     LinovelibSpider navigator.language.toLowerCase()=zh-tw                                                     linovelib_spider.py:718
                    INFO     LinovelibSpider  初始化 Driver 完毕...                                                                     linovelib_spider.py:725
Traceback (most recent call last):
  File "D:\linovelib2epub.clone\main.py", line 33, in <module>
    linovelib_epub.run()
    ~~~~~~~~~~~~~~~~~~^^
  File "D:\linovelib2epub.clone\src\linovelib2epub\linovel.py", line 445, in run
    novel = self._spider.fetch()
  File "D:\linovelib2epub.clone\src\linovelib2epub\spider\linovelib_spider.py", line 84, in fetch
    novel_whole = self._fetch_pc()
  File "D:\linovelib2epub.clone\src\linovelib2epub\spider\linovelib_spider.py", line 994, in _fetch_pc
    self._convert_page_language_pc(book_url)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\linovelib2epub.clone\src\linovelib2epub\spider\linovelib_spider.py", line 1031, in _convert_page_language_pc
    current_text = translate_btn.text
                   ^^^^^^^^^^^^^^^^^^
  File "D:\linovelib2epub.clone\.venv\Lib\site-packages\DrissionPage\_elements\none_element.py", line 38, in __getattr__
    raise ElementNotFoundError(None, self.method, self.args)
DrissionPage.errors.ElementNotFoundError:
没有找到元素。
method: ele()
args: {'locator': '#GB_BIG', 'index': 1, 'timeout': 10}
```
'timeout': 10 说明10秒钟都无法加载一个首页，推测是偶尔的网络问题，而不是bug。

**Comment by wdpm** [comment]
> 
![image](https://github.com/user-attachments/assets/232328ef-aa8e-475c-8970-0345b6fcfb5f)

这个截图说明浏览器访问的是mobile UI版本。而此项目目前已经放弃了mobile UI版本的维护，所以程序找不到ID是正常的行为。

理论上，程序期望访问的是下面截图的PC UI版本：

![image](https://github.com/user-attachments/assets/7d7780fa-ff1f-4ac5-bc2f-aad5621997ef)

URL: https://www.linovelib.com/novel/4126.html

**Comment by wdpm** [comment]
@Kuan-Lun 我需要你的一个反馈。因为我没法模拟你那边的网络环境。

下面是一个小实验，步骤如下：
1. 安装并打开chrome浏览器
2. 设置 -> 搜索“语言”，将“中文”设置为首选语言（注意不是中文（繁体）），访问 https://www.linovelib.com/ 链接
 观察此时页面会不会重定向到 tw.linovelib.com/XX，如果结果是会强制重定向，那么此bug暂时没有解决方案。如果结果是显示中文网站，并不会强制重定向，那么此问题理论上比较容易解决。

**Comment by wdpm** [comment]
更新代码，查看README，你可以重试一下。

**Comment by wdpm** [comment]
下面还需要继续实验来探索这个问题，从一个普通用户使用浏览器的角度：


https://github.com/user-attachments/assets/fe8449bb-883a-4e36-a656-58ce96e120e0

1. 打开chrome
2. 语言 -> 设置 【中文繁体】 置顶
3. 在浏览器搜索的列表页面 打开 https://www.linovelib.com/novel/4126.html 观察结果
4. 语言 -> 设置 【中文】 置顶
5. 在浏览器搜索的列表页面 打开 https://www.linovelib.com/novel/4126.html 观察结果

**Comment by Kuan-Lun** [comment]
https://github.com/user-attachments/assets/115d7334-8ed6-4edb-92b6-07d764331e91

**Comment by wdpm** [comment]
既然如此，那你设置chrome为中文，然后走以下代码问题不就解决了吗？
```python
from linovelib2epub import Linovelib2Epub, TargetSite

if __name__ == "__main__":
    linovelib_epub = Linovelib2Epub(
        book_id=4126,
        select_volume_mode=True,
        log_level="DEBUG",
        target_site=TargetSite.LINOVELIB_PC_TRADITIONAL,
    )
    linovelib_epub.run()
```
- 目前这个程序在设置 TargetSite.LINOVELIB_PC_TRADITIONAL 时，会在网页上点一下”繁体化“按钮切换语言为繁体文本的。

**Comment by Kuan-Lun** [comment]
https://github.com/user-attachments/assets/4482f8b6-dac7-4018-8456-0994727cd959

[螢幕錄製](https://fi.klwang.tw/share/n-Yh9X7a)

有辦法添加指令讓 chrome driver 指定使用【中文】而非【中文繁体】嗎？

**Comment by wdpm** [comment]
算了。我还是将mobile ui版本的爬虫重新捡起维护吧，否则繁体版的爬虫目前我想不到更直接的解决方案了。

**Comment by Kuan-Lun** [comment]
模組 distutils 在 Python 3.10 時就被棄用，且已於 Python 正式從標準庫移除。[參見[distutils--- 构建和安装 Python 模块](https://docs.python.org/zh-tw/3.10/library/distutils.html)]

```
D:\linovelib2epub.clone\src\linovelib2epub\utils.py:158: SyntaxWarning: invalid escape sequence '\-'
  """
Traceback (most recent call last):
  File "D:\linovelib2epub.clone\main.py", line 1, in <module>
    from linovelib2epub import Linovelib2Epub, TargetSite
  File "D:\linovelib2epub.clone\src\linovelib2epub\__init__.py", line 2, in <module>
    from .linovel import Linovelib2Epub, TargetSite
  File "D:\linovelib2epub.clone\src\linovelib2epub\linovel.py", line 22, in <module>
    from .spider import ASYNCIO, LinovelibSpiderMobile, LinovelibSpiderPC  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\linovelib2epub.clone\src\linovelib2epub\spider\__init__.py", line 3, in <module>
    from .linovelib_spider import LinovelibSpiderMobile,LinovelibSpiderPC
  File "D:\linovelib2epub.clone\src\linovelib2epub\spider\linovelib_spider.py", line 12, in <module>
    import inquirer
  File "D:\linovelib2epub.clone\.venv\Lib\site-packages\inquirer\__init__.py", line 1, in <module>
    from inquirer.prompt import prompt
  File "D:\linovelib2epub.clone\.venv\Lib\site-packages\inquirer\prompt.py", line 2, in <module>
    from inquirer.render.console import ConsoleRender
  File "D:\linovelib2epub.clone\.venv\Lib\site-packages\inquirer\render\__init__.py", line 1, in <module>
    from inquirer.render.console import ConsoleRender
  File "D:\linovelib2epub.clone\.venv\Lib\site-packages\inquirer\render\console\__init__.py", line 10, in <module>
    from inquirer.render.console._editor import Editor
  File "D:\linovelib2epub.clone\.venv\Lib\site-packages\inquirer\render\console\_editor.py", line 1, in <module>
    import editor
  File "D:\linovelib2epub.clone\.venv\Lib\site-packages\editor.py", line 11, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'
```

**Comment by wdpm** [comment]
> 模組 distutils 在 Python 3.10 時就被棄用，且已於 Python 3.12 正式從標準庫移除。[參見[distutils--- 构建和安装 Python 模块](https://docs.python.org/zh-tw/3.10/library/distutils.html) 與 [What’s New In Python 3.12](https://docs.python.org/3.12/whatsnew/3.12.html)]
> 
> ```
> D:\linovelib2epub.clone\src\linovelib2epub\utils.py:158: SyntaxWarning: invalid escape sequence '\-'
>   """
> Traceback (most recent call last):
>   File "D:\linovelib2epub.clone\main.py", line 1, in <module>
>     from linovelib2epub import Linovelib2Epub, TargetSite
>   File "D:\linovelib2epub.clone\src\linovelib2epub\__init__.py", line 2, in <module>
>     from .linovel import Linovelib2Epub, TargetSite
>   File "D:\linovelib2epub.clone\src\linovelib2epub\linovel.py", line 22, in <module>
>     from .spider import ASYNCIO, LinovelibSpiderMobile, LinovelibSpiderPC  # type: ignore[attr-defined]
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\linovelib2epub.clone\src\linovelib2epub\spider\__init__.py", line 3, in <module>
>     from .linovelib_spider import LinovelibSpiderMobile,LinovelibSpiderPC
>   File "D:\linovelib2epub.clone\src\linovelib2epub\spider\linovelib_spider.py", line 12, in <module>
>     import inquirer
>   File "D:\linovelib2epub.clone\.venv\Lib\site-packages\inquirer\__init__.py", line 1, in <module>
>     from inquirer.prompt import prompt
>   File "D:\linovelib2epub.clone\.venv\Lib\site-packages\inquirer\prompt.py", line 2, in <module>
>     from inquirer.render.console import ConsoleRender
>   File "D:\linovelib2epub.clone\.venv\Lib\site-packages\inquirer\render\__init__.py", line 1, in <module>
>     from inquirer.render.console import ConsoleRender
>   File "D:\linovelib2epub.clone\.venv\Lib\site-packages\inquirer\render\console\__init__.py", line 10, in <module>
>     from inquirer.render.console._editor import Editor
>   File "D:\linovelib2epub.clone\.venv\Lib\site-packages\inquirer\render\console\_editor.py", line 1, in <module>
>     import editor
>   File "D:\linovelib2epub.clone\.venv\Lib\site-packages\editor.py", line 11, in <module>
>     from distutils.spawn import find_executable
> ModuleNotFoundError: No module named 'distutils'
> ```

看起来像是inquirer这个库的旧版本不兼容python 3.13?

**Comment by Kuan-Lun** [comment]
### 套件安裝
如果使用 Microsoft Store 安裝 Python 就會是只有安裝好 pip 套件的 Python，即沒有預設安裝類色 setuptools 等套件。
此外，我注意到 `pyproject.toml` 與 `requirements.txt` 對於套件的要求並不一致。
是否有考慮統一下？

### 錯誤
觀察到當出現以下內容時，會漏掉部分該章節的內容。
```
（內容加載失敗！請重載或更換瀏覽器）
【手機版頁面由於相容性問題暫不支持電腦端閱讀，請使用手機閱讀。】
```
![圖片](https://github.com/user-attachments/assets/ad951b84-9a63-4f6a-a907-8bf48436a13f)

根據我觀察第一本的結果，只出現一次該問題。我建議加上一個刷新網頁的判斷，當出現上述文字時，重刷頁面已取得完整文章。

**Comment by wdpm** [comment]
> 如果使用 Microsoft Store 安裝 Python 就會是只有安裝好 pip 套件的 Python，即沒有預設安裝類色 setuptools 等套件。
此外，我注意到 pyproject.toml 與 requirements.txt 對於套件的要求並不一致。
是否有考慮統一下？

同意。pyproject.toml 是用于打包发布的构建文件（当然它也可以包含依赖定义），requirements_XXX.txt 是目前用于管理依赖的列表清单。pyproject.toml 中的定义是宽松的，你能看到 >= 这种取下限的版本范围，而requirements_XXX.txt是固定版本的，为了尽可能避免下载时依赖库版本不一致导致各种奇怪问题。目前你看到 pyproject.toml 有些依赖缺失是因为我忘记更新了。总之，你先以 requirements.txt 为准，文档说明中也是以 requirements.txt为准。

**Comment by wdpm** [comment]
> 觀察到當出現以下內容時，會漏掉部分該章節的內容。

（內容加載失敗！請重載或更換瀏覽器）
【手機版頁面由於相容性問題暫不支持電腦端閱讀，請使用手機閱讀。】

![image](https://github.com/user-attachments/assets/3518e3ce-2319-4ed3-adaa-67d171291519)


根據我觀察第一本的結果，只出現一次該問題。我建議加上一個刷新網頁的判斷，當出現上述文字時，重刷頁面已取得完整文章。

tips：issue类问题最好附上重现步骤，至少你应该提供一个出现该问题的示例url，我才能进行下一步分析。你的举手之劳很可能能为我节省一大段的时间。另外，这个issue已经偏移你一开始的那个issue很远了。我推荐关闭此issue，对于别的问题，你可以逐个发起新的issue。@Kuan-Lun
